# Generated by Django 2.2 on 2019-04-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NEWS_ID', models.TextField(default='', max_length=32)),
                ('TITLE', models.TextField(default='', max_length=32)),
                ('AUTHOR', models.CharField(default='', max_length=255)),
                ('URL', models.CharField(default='', max_length=255)),
                ('KEYWORDS', models.CharField(default='', max_length=100)),
                ('SOURCE', models.CharField(default='', max_length=16)),
                ('CREATE_TIME', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCOUNT', models.CharField(default='', max_length=32)),
                ('PASSWORD', models.CharField(default='', max_length=32)),
                ('ROLE', models.CharField(default='', max_length=10)),
                ('CREATE_TIME', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
